// Code generated by MockGen. DO NOT EDIT.
// Source: go-boilerplate-rest-api-chi/internal/database/sqlc (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_querier.go -package=mocks go-boilerplate-rest-api-chi/internal/database/sqlc Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sqlc "go-boilerplate-rest-api-chi/internal/database/sqlc"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountBooks mocks base method.
func (m *MockQuerier) CountBooks(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBooks", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBooks indicates an expected call of CountBooks.
func (mr *MockQuerierMockRecorder) CountBooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBooks", reflect.TypeOf((*MockQuerier)(nil).CountBooks), ctx)
}

// CreateAuthor mocks base method.
func (m *MockQuerier) CreateAuthor(ctx context.Context, arg sqlc.CreateAuthorParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthor", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuthor indicates an expected call of CreateAuthor.
func (mr *MockQuerierMockRecorder) CreateAuthor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthor", reflect.TypeOf((*MockQuerier)(nil).CreateAuthor), ctx, arg)
}

// CreateBook mocks base method.
func (m *MockQuerier) CreateBook(ctx context.Context, arg sqlc.CreateBookParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockQuerierMockRecorder) CreateBook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockQuerier)(nil).CreateBook), ctx, arg)
}

// DeleteBook mocks base method.
func (m *MockQuerier) DeleteBook(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockQuerierMockRecorder) DeleteBook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockQuerier)(nil).DeleteBook), ctx, id)
}

// GetAllBooks mocks base method.
func (m *MockQuerier) GetAllBooks(ctx context.Context) ([]sqlc.GetAllBooksRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBooks", ctx)
	ret0, _ := ret[0].([]sqlc.GetAllBooksRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBooks indicates an expected call of GetAllBooks.
func (mr *MockQuerierMockRecorder) GetAllBooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBooks", reflect.TypeOf((*MockQuerier)(nil).GetAllBooks), ctx)
}

// GetAuthorByID mocks base method.
func (m *MockQuerier) GetAuthorByID(ctx context.Context, id string) (sqlc.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorByID indicates an expected call of GetAuthorByID.
func (mr *MockQuerierMockRecorder) GetAuthorByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorByID", reflect.TypeOf((*MockQuerier)(nil).GetAuthorByID), ctx, id)
}

// GetBookByID mocks base method.
func (m *MockQuerier) GetBookByID(ctx context.Context, id string) (sqlc.GetBookByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByID", ctx, id)
	ret0, _ := ret[0].(sqlc.GetBookByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByID indicates an expected call of GetBookByID.
func (mr *MockQuerierMockRecorder) GetBookByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByID", reflect.TypeOf((*MockQuerier)(nil).GetBookByID), ctx, id)
}

// UpdateBook mocks base method.
func (m *MockQuerier) UpdateBook(ctx context.Context, arg sqlc.UpdateBookParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockQuerierMockRecorder) UpdateBook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockQuerier)(nil).UpdateBook), ctx, arg)
}
