// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: author.sql

package sqlc

import (
	"context"
)

const createAuthor = `-- name: CreateAuthor :exec
INSERT INTO authors (id, name)
VALUES (?, ?)
`

type CreateAuthorParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, createAuthor, arg.ID, arg.Name)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name
FROM authors
WHERE id = ?
`

func (q *Queries) GetAuthorByID(ctx context.Context, id string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
