// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book.sql

package sqlc

import (
	"context"
)

const countBooks = `-- name: CountBooks :one
SELECT count(*) FROM books
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :exec
INSERT INTO books (id, title, description, author_id)
VALUES (?, ?, ?, ?)
`

type CreateBookParams struct {
	ID          string
	Title       string
	Description string
	AuthorID    string
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) error {
	_, err := q.db.ExecContext(ctx, createBook,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
	)
	return err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getAllBooks = `-- name: GetAllBooks :many
SELECT
    books.id,
    books.title,
    books.description,
    authors.id   AS author_id,
    authors.name AS author_name
FROM books
JOIN authors ON authors.id = books.author_id
ORDER BY books.id
`

type GetAllBooksRow struct {
	ID          string
	Title       string
	Description string
	AuthorID    string
	AuthorName  string
}

func (q *Queries) GetAllBooks(ctx context.Context) ([]GetAllBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllBooksRow{}
	for rows.Next() {
		var i GetAllBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByID = `-- name: GetBookByID :one
SELECT
    books.id,
    books.title,
    books.description,
    authors.id   AS author_id,
    authors.name AS author_name
FROM books
JOIN authors ON authors.id = books.author_id
WHERE books.id = ?
`

type GetBookByIDRow struct {
	ID          string
	Title       string
	Description string
	AuthorID    string
	AuthorName  string
}

func (q *Queries) GetBookByID(ctx context.Context, id string) (GetBookByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i GetBookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.AuthorName,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title = ?, description = ?
WHERE id = ?
`

type UpdateBookParams struct {
	Title       string
	Description string
	ID          string
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.ExecContext(ctx, updateBook, arg.Title, arg.Description, arg.ID)
	return err
}
