// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Author struct {
	ID   string
	Name string
}

type Book struct {
	ID          string
	Title       string
	Description string
	AuthorID    string
}
