// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountBooks(ctx context.Context) (int64, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) error
	CreateBook(ctx context.Context, arg CreateBookParams) error
	DeleteBook(ctx context.Context, id string) error
	GetAllBooks(ctx context.Context) ([]GetAllBooksRow, error)
	GetAuthorByID(ctx context.Context, id string) (Author, error)
	GetBookByID(ctx context.Context, id string) (GetBookByIDRow, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) error
}

var _ Querier = (*Queries)(nil)
